name: 'Docker Action'
description: 'some desc'
inputs:
  who-to-greet:
    description: 'who to greet'
    required: true
    default: 'world'
outputs:
  time:
    description: 'time'
runs: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
