name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: environment
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "event name: ${{ github.event_name }}"
          echo "branch name ${{ github.ref }} and your repository is ."
      - uses: actions/checkout@v3.3.0
      - name: List files in the repository
        run: | 
          echo "The repository ${{ github.repository }} contains the following files:"
          tree

  Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'workfolw_dispatch'
    environment: Test
    steps:
      - run: |
          echo 'Testing...'
          sleep 15
      

  Load-Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'workfolw_dispatch'
    environment: Load-Test
    steps:
      - run: |
          echo 'Load Testing...'
          sleep 15

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment:
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: |
          echo 'Step 1 deploying...'
          sleep 10
      - run:  |
          echo 'Step 2 deploying...'
          sleep 10
      - run: |
          echo 'Step 3 deploying...'
          sleep 10
      - run: |
          echo 'Step 4 deploying...'
          sleep 10
      - run: |
          echo 'Step 5 deploying...'
          sleep 10
    
    
