name: Docker workflow
on:
  push:
    paths: [ hello-world-docker-action/** ]
  workflow_dispatch:
jobs:
  some-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions.checkout@v3.3.0
      - name: call action
        id: call-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: 'qwe'
      - name: output
        run: echo "time was ${{ steps.call-action.outputs.time }}"
    
